# Generated by Django 3.1.6 on 2021-03-08 07:24

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210308_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name=blog.models.Post),
        ),
    ]
